### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Judeoracle** [soramitsu/fearless-iOS#293]
Sorry if this is not the right place, but I’m having trouble using with my Fearless wallet. I recently sent two deposits, but they are not showing up.

Where do I go to get help with this?

**Comment by ERussel** [comment]
> Sorry if this is not the right place, but I’m having trouble using with my Fearless wallet. I recently sent two deposits, but they are not showing up.
> 
> Where do I go to get help with this?

Hey! Please, join our Telegram support group https://t.me/fearlesswallet_support. Alternatively, you can contact support by email in the app (Settings -> About -> Contact Us)
